FROM public.ecr.aws/lambda/python:3.8

COPY helper_functions.py score.py ${LAMBDA_TASK_ROOT}/

RUN  pip3 install awswrangler \
                    scikit-learn \
                    pandas \
                    boto3 \
                    --target "${LAMBDA_TASK_ROOT}"

CMD [ "score.lambda_handler" ]
# CMD ["tail", "-f", "/dev/null"]


