services:
  s3:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
  lambda:
    image: lambda_img:latest
    network_mode: "host"
    environment:
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - ARTIFACT_BUCKET_NAME=$ARTIFACT_BUCKET_NAME
      - INFERENCE_BUCKET_NAME=$INFERENCE_BUCKET_NAME
      - S3_ENDPOINT=http://localhost:4566