name: ci

on:
  pull_request:
    branches:
      - "development"
  push:
    branches:
      - "development"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ARTIFACT_BUCKET_NAME: ${{ secrets.ARTIFACT_BUCKET_NAME }}
  INFERENCE_BUCKET_NAME: ${{ secrets.INFERENCE_BUCKET_NAME }}

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        make install

    - name: Run tests
      env:
        AWS_REGION: sa-east-1
      run: |
        make tests


