
name: Deploy
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:

# Set up
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"
          ARTIFACT_BUCKET_NAME: ${{ secrets.ARTIFACT_BUCKET_NAME }}
          INFERENCE_BUCKET_NAME: ${{ secrets.INFERENCE_BUCKET_NAME }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          
# Build-Push
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push Images
        id: build-image
        working-directory: "src/deployment"
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: "latest"
        run: |
          docker build -t ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image_uri::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
      
# Deploy
      - name: npm install dependencies
        run: npm install
      
      - name: Serverless
        uses: serverless/github-action@v1.53.0
        with:
          args: deploy